### ISSUE TITLE
[Intermittent] Navigating to a website by previously typing the "s" character in the address bar doesn't generate the "frecency" ping

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [florian/federated-learning-addon#9] opened 2018-07-11 15:36 UTC
[Affected versions]:
- Beta Version 62.0b7
- Dev Edition Version 62.0b7

[Affected Platforms]:
- Windows 10 x64

[Prerequisites]:
- Federated Learning add-on is installed.
- At least 1 website is in History.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Open a new tab and click on the Awesome bar.
3. Press the "S" key and select any of the previously visited websites from the dropdown list.
4. Open the "about:telemetry" page and observe the archived pings.

[Expected result]:
- The frecency ping is correctly displayed.

[Actual result]:
- The frecency ping is not displayed.

[Notes]:
- The issue appeared on 2 different testing stations.
- The issue was also reproducible for a limited time with the "w" and "m" keys.
- We didn't encounter this issue on Linux and MacOS so far.
- The following errors are displayed in the browser console randomly regardless of website:

 ```
[Show/hide message details.] res[0] is undefined api.js:36
calculateByURL
jar:file:///C:/Users/patriciu.pop/AppData/Roaming/Mozilla/Firefox/Profiles/u8q8e5es.123/extensions/federated-learning@shield.mozilla.org.xpi!/experiments/frecency/api.js:36:13
next self-hosted:1222:9 
```

```
[Show/hide message details.] res[0] is undefined api.js:36
calculateByURL
jar:file:///C:/Users/patriciu.pop/AppData/Roaming/Mozilla/Firefox/Profiles/u8q8e5es.123/extensions/federated-learning@shield.mozilla.org.xpi!/experiments/frecency/api.js:36:13
InterpretGeneratorResume self-hosted:1267:8 next self-hosted:1222:9 permitUnload
chrome://global/content/bindings/remote-browser.xml:373:13
_loadURI
chrome://browser/content/browser.js:1046:38
loadURI
chrome://browser/content/tabbrowser.xml:2169:13
openLinkIn
chrome://browser/content/utilityOverlay.js:512:5
openUILinkIn
chrome://browser/content/utilityOverlay.js:269:3
openTrustedLinkIn
chrome://browser/content/utilityOverlay.js:203:3
_loadURL
chrome://browser/content/urlbarBindings.xml:887:13
handleCommand
chrome://browser/content/urlbarBindings.xml:811:11
anonymous
chrome://global/content/bindings/autocomplete.xml line 422 > Function:3:1
anonymous self-hosted:1030:17 onTextEntered
chrome://global/content/bindings/autocomplete.xml:256:18
handleEnter
chrome://browser/content/urlbarBindings.xml:1526:25
handleKeyPress
chrome://global/content/bindings/autocomplete.xml:503:24
onKeyPress
chrome://browser/content/urlbarBindings.xml:283:18
onxblkeypress
chrome://global/content/bindings/autocomplete.xml:617:8
```

- I have attached a screencast of the issue showing the 2 console errors.
![console errors](https://user-images.githubusercontent.com/40393891/42583029-f8ab190e-8538-11e8-8368-15bd5a498eaa.gif)

**Comment by florian** [comment] 2018-07-12 18:11
Good catch! I was able to reproduce this with different URLs.
It's independent of the search query but has to do with different features of the displayed suggestions.

https://github.com/florian/federated-learning-addon/commit/ddac936add0c369b869da4ed3f34f6663abbc044#diff-b3d5c05a3e16a39b910d06d9e6fa8b54 should hopefully fix this.
I've sent Carmen a new build with this fix.

**Comment by SoftVision-CarmenFat** [comment] 2018-07-13 15:29
Tested this with the latest .xpi from the email and the issue seems to be fixed. Since it's no longer reproducible, I'm going to close this report.

**Closed** 2018-07-13 15:30 UTC
Labels: awaiting-qa-response
